# Uncomment to enable the encoder
CONFIG_EC11=y
CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_RGB_UNDERGLOW=y

CONFIG_BUILD_OUTPUT_HEX=y


# CONFIG_ZMK_RTT_LOGGING=y

CONFIG_HW_STACK_PROTECTION=y
CONFIG_MPU_STACK_GUARD=y

CONFIG_NVS_INIT_BAD_MEMORY_REGION=y
# CONFIG_LOG_BACKEND_RTT_BUFFER_SIZE=16384
CONFIG_LOG_PROCESS_THREAD=y

# Turn on logging, and set ZMK logging to debug output
CONFIG_LOG=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
CONFIG_ZMK_USB_LOGGING=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_LOG_BUFFER_SIZE=20000    
CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_SPI_LOG_LEVEL_DBG=y
CONFIG_DISPLAY_LOG_LEVEL_DBG=y
CONFIG_LV_LOG_LEVEL_TRACE=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y

# Make display initialize really late
CONFIG_DISPLAY_INIT_PRIORITY=98
CONFIG_LV_Z_INIT_PRIORITY=99